/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline-variant": "var(--border)",
        "outline": "var(--border-md)",
        "tertiary": "var(--bg-subtle)",
        "secondary-fixed": "var(--teal-300)",
        "on-surface": "var(--text-primary)",
        "secondary-fixed-dim": "var(--teal-400)",
        "surface-tint": "var(--teal-600)",
        "on-primary-fixed-variant": "var(--teal-900)",
        "secondary-container": "var(--teal-300)",
        "primary-fixed": "var(--teal-100)",
        "surface-bright": "var(--bg-card)",
        "tertiary-fixed-dim": "var(--bg-muted)",
        "primary-fixed-dim": "var(--teal-200)",
        "on-primary-fixed": "var(--teal-950)",
        "primary": "var(--primary)",
        "surface-container-highest": "var(--bg-subtle)",
        "primary-container": "var(--primary-container)",
        "surface-dim": "var(--bg-page)",
        "surface-container-lowest": "var(--bg-page)",
        "tertiary-fixed": "var(--bg-subtle)",
        "on-secondary-container": "var(--teal-800)",
        "background": "var(--bg-page)",
        "on-secondary": "#ffffff",
        "tertiary-container": "var(--bg-muted)",
        "surface-variant": "var(--bg-muted)",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "var(--teal-900)",
        "on-tertiary-container": "var(--text-muted)",
        "on-primary-container": "var(--teal-400)",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface": "var(--bg-card)",
        "inverse-surface": "var(--text-primary)",
        "on-secondary-fixed": "var(--teal-950)",
        "surface-container-low": "var(--bg-page)",
        "on-tertiary-fixed": "var(--text-primary)",
        "on-surface-variant": "var(--text-secondary)",
        "surface-container-high": "var(--bg-card)",
        "on-tertiary": "#ffffff",
        "surface-container": "var(--bg-page)",
        "secondary": "var(--secondary)",
        "inverse-primary": "var(--teal-400)",
        "inverse-on-surface": "var(--bg-page)",
        "on-background": "var(--text-primary)",
        "on-tertiary-fixed-variant": "var(--text-secondary)",
        "on-primary": "#ffffff",
        "on-error": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "4px",
        "md": "16px",
        "xs": "4px",
        "gutter": "24px",
        "lg": "24px",
        "xxl": "64px",
        "sm": "8px",
        "xl": "40px",
        "container-max": "1280px"
      },
      "fontFamily": {
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-xl": ["Public Sans"],
        "headline-lg": ["Public Sans"],
        "headline-md": ["Public Sans"],
        "body-lg": ["Inter"],
        "public-sans": ["Public Sans"]
      },
      "fontSize": {
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-xl": ["40px", {"lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      },
      "animation": {
        'fade-up': 'fadeUp 0.25s ease-out',
        'pulse-dot': 'pulseDot 1.4s ease-in-out infinite',
      },
      "keyframes": {
        fadeUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseDot: {
          '0%, 80%, 100%': { transform: 'scale(0.6)', opacity: '0.4' },
          '40%': { transform: 'scale(1)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};
